version: '3'
services:
  mysql:
    build:
      dockerfile: Dockerfile.dev
      context: ./db/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=*******
    volumes:
      - ./db/mysql/volume:/var/lib/mysql
  postgres:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=*******
      - POSTGRES_PASSWORD=*******
      - POSTGRES_DB=demo
    build:
      dockerfile: Dockerfile.dev
      context: ./db/postgres
    volumes:
      - ./db/postgres/volume:/var/lib/postgresql
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379
    volumes:
      - ./db/redis/volume:/data
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=*******
      - MONGO_INITDB_ROOT_PASSWORD=*******
    ports:
      - 27019:27017
    build:
      dockerfile: Dockerfile.dev
      context: ./db/mongo
    volumes:
      - ./db/mongo/volume:/data/db
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
#          - redis
          - postgres
#          - mongo
#          - mysql
    environment:
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=demo
      - PGUSER=*******
      - PGPASSWORD=*******
      # Mysql
      - MYSQLHOST=mysql
      - MYSQLPORT=3306
      - MYSQLDATABASE=demo
      - MYSQLUSER=root
      - MYSQLPASSWORD=*******
      # Mongo
      - MONGOHOST=mongo
      - MONGOPORT=27017
      - MONGODATABASE=demo
      - MONGOUSER=*******
      - MONGOPASSWORD=*******
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
          - api
